from matplotlib import pyplot as ppl
datax=[]
x1=int(input("x1: "))
datax.append(x1)
x2=int(input("x2: "))
datax.append(x2)
x3=int(input("x3: "))
datax.append(x3)
x4=int(input("x4: "))
datax.append(x4)
x5=int(input("x5: "))
datax.append(x5)
datay=[]
y1=input("y1: ")
datay.append(y1)
y2=input("y2: ")
datay.append(y2)
y3=input("y3: ")
datay.append(y3)
y4=input("y4: ")
datay.append(y4)
y5=input("y5: ")
datay.append(y5)
ppl.plot(datax,datay)
ppl.xlabel("profit")
ppl.ylabel("year")
ppl.title("Profit graph")
ppl.show()